"""What idiot decided that user and plan is the primary key of active plan?

Revision ID: 36c429315137
Revises: 215e1b0666f6
Create Date: 2023-04-14 19:33:56.984929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c429315137'
down_revision = '215e1b0666f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_plans', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column("active_plans", "user_id", primary_key=False)
    op.alter_column("active_plans", "plan_id", primary_key=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_plans', 'id')
    op.alter_column("active_plans", "user_id", primary_key=True)
    op.alter_column("active_plans", "plan_id", primary_key=True)
    # ### end Alembic commands ###
