"""add telegram_id

Revision ID: 371a662a6abd
Revises: a87746eb691c
Create Date: 2023-03-12 13:56:25.475242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371a662a6abd'
down_revision = 'a87746eb691c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
