"""Removed multiple subscriptions feature

Revision ID: 393513b67834
Revises: a52ad748d00d
Create Date: 2023-03-25 16:10:42.270103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393513b67834'
down_revision = 'a52ad748d00d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_renewable_plans')
    op.add_column('users', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'plans', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    op.create_table('auto_renewable_plans',
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='auto_renewable_plans_plan_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='auto_renewable_plans_user_id_fkey'),
    sa.PrimaryKeyConstraint('plan_id', 'user_id', name='auto_renewable_plans_pkey')
    )
    # ### end Alembic commands ###
