"""is_extra and months instead of periods

Revision ID: 3a021e58f655
Revises: 393513b67834
Create Date: 2023-03-25 20:20:23.906276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3a021e58f655'
down_revision = '393513b67834'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('months', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('is_extra', sa.Boolean(), nullable=True))
    op.drop_column('plans', 'period')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('period', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'is_extra')
    op.drop_column('plans', 'months')
    # ### end Alembic commands ###
