"""Plans reworked

Revision ID: 4b6b0f453740
Revises: eb12aaab9410
Create Date: 2023-03-18 15:17:21.055182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b6b0f453740'
down_revision = 'eb12aaab9410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('active_plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('calls_left', sa.Integer(), nullable=True),
    sa.Column('messages_left', sa.Integer(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'plan_id')
    )
    op.create_table('auto_renewable_plans',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'user_id')
    )
    op.create_table('plan_options',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('plan_id', 'option_id')
    )
    op.add_column('messages', sa.Column('extra_data', sa.JSON(), nullable=False))
    op.add_column('plans', sa.Column('calls', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('messages', sa.Integer(), nullable=True))
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('plans_name_key', 'plans', type_='unique')
    op.drop_column('plans', 'incoming_calls_limit')
    op.drop_column('plans', 'outgoing_calls_limit')
    op.drop_column('plans', 'messages_limit')
    op.drop_constraint('users_plan_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'subsciption_end')
    op.drop_column('users', 'incoming_calls_made')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'messages_sent')
    op.drop_column('users', 'outgoing_calls_made')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('outgoing_calls_made', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('messages_sent', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('incoming_calls_made', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('subsciption_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_plan_id_fkey', 'users', 'plans', ['plan_id'], ['id'])
    op.add_column('plans', sa.Column('messages_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('outgoing_calls_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('incoming_calls_limit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('plans_name_key', 'plans', ['name'])
    op.alter_column('plans', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('plans', 'messages')
    op.drop_column('plans', 'calls')
    op.drop_column('messages', 'extra_data')
    op.drop_table('plan_options')
    op.drop_table('auto_renewable_plans')
    op.drop_table('active_plans')
    op.drop_table('options')
    # ### end Alembic commands ###
