"""Add plans and user fields

Revision ID: 6451fca7849c
Revises: 371a662a6abd
Create Date: 2023-03-14 18:56:33.760915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6451fca7849c'
down_revision = '371a662a6abd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('period', sa.Interval(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # op.alter_column('messages', 'author_id', new_column_name='author')
    op.add_column('users', sa.Column('first_name', sa.String(length=48), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=48), nullable=True))
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'plan_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # op.alter_column('messages', 'author', new_column_name='author_id')
    op.drop_table('plans')
    # ### end Alembic commands ###
