"""CP token added

Revision ID: 7a2bebb723e4
Revises: dbd8b4a00c81
Create Date: 2023-04-18 00:04:20.338241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a2bebb723e4'
down_revision = 'dbd8b4a00c81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_token', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['payment_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'payment_token')
    # ### end Alembic commands ###
