"""added tables for amoCRM

Revision ID: 910113bde36e
Revises: b9cd6ae37b98
Create Date: 2023-05-07 16:39:27.697383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910113bde36e'
down_revision = 'b9cd6ae37b98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('busy_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busy_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amo_contacts_busy_user_id'), 'amo_contacts', ['busy_user_id'], unique=True)
    op.create_table('amo_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['amo_contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amo_leads')
    op.drop_index(op.f('ix_amo_contacts_busy_user_id'), table_name='amo_contacts')
    op.drop_table('amo_contacts')
    # ### end Alembic commands ###
