"""added column 'gender' to users

Revision ID: 910bef04a316
Revises: 001
Create Date: 2024-05-17 22:18:45.100415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '910bef04a316'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
