"""Billing changes

Revision ID: 9d78309f8d3b
Revises: b5cbdb47fdc7
Create Date: 2023-04-18 20:39:10.593985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d78309f8d3b'
down_revision = 'b5cbdb47fdc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payment_method_string', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_method_string')
    # ### end Alembic commands ###
