"""Add call and message

Revision ID: a52ad748d00d
Revises: 4b6b0f453740
Create Date: 2023-03-18 15:54:25.028849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a52ad748d00d'
down_revision = '4b6b0f453740'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('callee_number', sa.String(length=20), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('recording_url', sa.String(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.add_column('messages', sa.Column('uid', sa.Uuid(), nullable=False))
    op.add_column('messages', sa.Column('call_uid', sa.Uuid(), nullable=False))
    op.add_column('messages', sa.Column('command', sa.String(length=16), nullable=False))
    op.alter_column('messages', 'contents',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using='contents::json')
    # op.drop_constraint('messages_author_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'calls', ['call_uid'], ['uid'])
    op.drop_column('messages', 'extra_data')
    # op.drop_column('messages', 'author_id')
    op.drop_column('messages', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # op.add_column('messages', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('extra_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    # op.create_foreign_key('messages_author_id_fkey', 'messages', 'users', ['author_id'], ['id'])
    op.alter_column('messages', 'contents',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('messages', 'command')
    op.drop_column('messages', 'call_uid')
    op.drop_column('messages', 'uid')
    op.drop_table('calls')
    # ### end Alembic commands ###
