"""Added user_id into scheduled action

Revision ID: a7bb57583a99
Revises: 91cac04b696f
Create Date: 2023-04-23 15:38:58.589996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a7bb57583a99'
down_revision = '91cac04b696f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_actions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scheduled_actions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_actions', type_='foreignkey')
    op.drop_column('scheduled_actions', 'user_id')
    # ### end Alembic commands ###
