"""Initial DB structure

Revision ID: a87746eb691c
Revises: 
Create Date: 2023-03-07 16:01:49.183707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87746eb691c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('own_phone', sa.String(length=20), nullable=False),
    sa.Column('given_phone', sa.String(length=20), nullable=False),
    sa.Column('subsciption_end', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_given_phone'), 'users', ['given_phone'], unique=False)
    op.create_index(op.f('ix_users_own_phone'), 'users', ['own_phone'], unique=True)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_own_phone'), table_name='users')
    op.drop_index(op.f('ix_users_given_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
