"""Scheduled actions and billing changes

Revision ID: b5cbdb47fdc7
Revises: 7a2bebb723e4
Create Date: 2023-04-18 17:56:57.300279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5cbdb47fdc7'
down_revision = '7a2bebb723e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('active_plans', sa.Column('payment_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('pending_payment_id', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['pending_payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pending_payment_id')
    op.drop_column('active_plans', 'payment_id')
    op.drop_table('scheduled_actions')
    # ### end Alembic commands ###
