"""Add preferences

Revision ID: c86a28d1b7e4
Revises: 2c11f5a5decf
Create Date: 2023-04-24 16:21:55.618734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86a28d1b7e4'
down_revision = '2c11f5a5decf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    preferences_table = op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('values_override', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['preferences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.bulk_insert(preferences_table, [
        dict(id=0, parent_id=None, values_override=dict(_comment="Put default preferences here manually")),
    ])
    op.add_column('users', sa.Column('preferences_id', sa.Integer(), nullable=False, server_default="0"))
    op.alter_column('users', 'preferences_id', server_default=None)
    op.create_foreign_key(None, 'users', 'preferences', ['preferences_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'preferences_id')
    op.drop_table('preferences')
    # ### end Alembic commands ###
