"""Fixes for sessions&auth

Revision ID: ce924ccb6d0a
Revises: 6e2f201a20d5
Create Date: 2023-04-02 00:13:24.955441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce924ccb6d0a'
down_revision = '6e2f201a20d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_codes', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('auth_codes', sa.Column('used', sa.Boolean(), nullable=False))
    op.drop_constraint('auth_codes_request_id_fkey', 'auth_codes', type_='foreignkey')
    op.drop_column('auth_codes', 'request_id')
    op.add_column('auth_sessions', sa.Column('expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'expired')
    op.add_column('auth_codes', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('auth_codes_request_id_fkey', 'auth_codes', 'auth_requests', ['request_id'], ['id'])
    op.drop_column('auth_codes', 'used')
    op.drop_column('auth_codes', 'phone')
    # ### end Alembic commands ###
