"""added session_id and timestamp to calls table

Revision ID: dbd8b4a00c81
Revises: 36c429315137
Create Date: 2023-04-15 12:20:52.052896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd8b4a00c81'
down_revision = '36c429315137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('calls', sa.Column('session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calls', 'session_id')
    op.drop_column('calls', 'timestamp')
    # ### end Alembic commands ###