"""call limits

Revision ID: eb12aaab9410
Revises: 6451fca7849c
Create Date: 2023-03-17 18:38:10.574588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb12aaab9410'
down_revision = '6451fca7849c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('incoming_calls_limit', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('plans', sa.Column('outgoing_calls_limit', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('plans', sa.Column('messages_limit', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('incoming_calls_made', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('outgoing_calls_made', sa.Integer(), nullable=False, server_default="0"))
    op.add_column('users', sa.Column('messages_sent', sa.Integer(), nullable=False, server_default="0"))
    
    op.alter_column('plans', 'incoming_calls_limit', server_default=None)
    op.alter_column('plans', 'outgoing_calls_limit', server_default=None)
    op.alter_column('plans', 'messages_limit', server_default=None)
    op.alter_column('users', 'incoming_calls_made', server_default=None)
    op.alter_column('users', 'outgoing_calls_made', server_default=None)
    op.alter_column('users', 'messages_sent', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'outgoing_calls_made')
    op.drop_column('users', 'incoming_calls_made')
    op.drop_column('users', 'messages_sent')
    op.drop_column('plans', 'outgoing_calls_limit')
    op.drop_column('plans', 'incoming_calls_limit')
    op.drop_column('plans', 'messages_limit')
    # ### end Alembic commands ###
