"""Fix

Revision ID: fe2eb3b50738
Revises: ce924ccb6d0a
Create Date: 2023-04-02 00:50:29.290555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2eb3b50738'
down_revision = 'ce924ccb6d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_banned_phones')
    op.create_table('auth_banned_phones',
                    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
                    sa.Column('phone', sa.String(length=20), nullable=False),
                    sa.Column('reason', sa.Text(), nullable=True),
                    sa.Column('start', sa.DateTime(), nullable=False),
                    sa.Column('end', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'phone')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
